'use client'

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { useEffect } from "react";
import { auth } from "@/lib/firebase";
import { onAuthStateChanged } from "firebase/auth";
import { useAuthStore } from "@/store/useAuthStore";
import IncomingCallListener from "@/components/call/IncomingCallListener";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {



  const setUser = useAuthStore((s) => s.setUser);


//bridge between Firebase and UI, because Firebase handles authentication internally, React app doesn’t automatically know: when user logs in, logs out or when page reload happens.
//onAuthStateChanged is listener from firebse in local globel state(zustand)

  useEffect(() => {
    const unsub = onAuthStateChanged(auth, (user) => {  
      setUser(user);
    });

    return () => unsub();
  }, []);

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Toaster position="top-center" />
        <IncomingCallListener />
        {children}
        </body>
    </html>
  );
}
